#!/bin/bash

source ./cybrtest.config

export CURL="curl -s"
export BASE_URL=http://localhost:8080/cybr
export DEBUG=true

main() {
export DRIVER_DEBUG=true
export PASJAVA_DEBUG=true
export CONJURJAVA_DEBUG=true
export JAVAREST_DEBUG=true

  java -cp ../build/lib/CybrDriver.jar:../build/dependencies/mysql-connector-java-8.0.25.jar -Dhttps.protocols=TLSv1.2 CybrDriver

}


###################################
test() {
  if ! $DEBUG; then return; fi
  local funcname=$1; shift
  local value="$(echo $1 | tr -d '\r\n')"; shift

  if [[ $value == null ]]; then
    echo "$funcname returned null."
  else
    echo "$funcname returned:"
    echo "$value"
    echo
  fi
}

main "$@"
