#!/bin/bash

source ./cybrtest.config

export CURL="curl -s"
export BASE_URL=http://localhost:8080/cybr
export DEBUG=true

main() {
  # Login as admin to PAS
  PASauthnCreds=$(echo "$PAS_ADMIN_NAME:$PAS_ADMIN_PASSWORD" | base64)
  pasAuthnResponse=$($CURL -H "Authorization: Basic $PASauthnCreds" -H "Content-Type: application/json" "$BASE_URL/pas/login")
  test "paslogin" "$pasAuthnResponse"

  safeResponse=$($CURL -H "Content-Type: application/json" "$BASE_URL/safe?safeName=PetClinicFoo")
  test "safes" "$safeResponse"

  exit

  userResponse=$($CURL -H "Content-Type: application/json" "$BASE_URL/user?userName=Admin1")
  test "users" "$userResponse"


  prResponse=$($CURL -H "Content-Type: application/json" "$BASE_URL/project")
  test "projects" "$prResponse"

  prResponse=$($CURL -H "Content-Type: application/json" "$BASE_URL/project?projectName=user1")
  test "projects" "$prResponse"
  govResponse=$($CURL -H "Content-Type: application/json" "$BASE_URL/governance")
  test "governance" "$govResponse"
}

###################################
test() {
  if ! $DEBUG; then return; fi
  local funcname=$1; shift
  local value="$(echo $1 | tr -d '\r\n')"; shift

  if [[ $value == null ]]; then
    echo "$funcname returned null."
  else
    echo "$funcname returned:"
    echo "$value"
    echo
  fi
}

main "$@"
