#!/bin/bash

# This test script exercises the servlet endpoints that are called
# from the ProvisioningServlet. It simulates the provisioning flow 
# of the ProvisioningServlet.doPost() function using values that are
# supplied as environment variables, rather than pulled from the appgovdb.

source ./cybrtest.config

export CURL="curl -s"
export BASE_URL=http://localhost:8080/cybr
export DEBUG=true

# accessrequest json record (for reference, not used here)
jsonTest="{\"projectName\":\"$PROJECT_NAME\",\"requestor\":\"$PROJECT_REQUESTOR\", \"approved\": 0, \"environment\":\"$PROJECT_ENVIRONMENT\", \"pasVaultName\":\"$PAS_VAULT_NAME\", \"pasSafeName\":\"$PAS_SAFE_NAME\", \"pasCpmName\":\"$PAS_CPM_NAME\", \"pasLobName\":\"$PAS_LOB_NAME\", \"appIdName\":\"$PROJECT_IDENTITY\", \"appAuthnMethod\":\"authn-k8s\"}"

main() {
  # Login as admin to PAS
  PASauthnCreds=$(echo "$PAS_ADMIN_NAME:$PAS_ADMIN_PASSWORD" | base64)
  pasAuthnResponse=$($CURL -H "Authorization: Basic $PASauthnCreds" -H "Content-Type: application/json" "$BASE_URL/pas/login")
  test "paslogin" "$pasAuthnResponse"

  # Login as admin to Conjur
  ConjurAuthnCreds=$(echo "$CONJUR_ADMIN_NAME:$CONJUR_ADMIN_PASSWORD" | base64)
  conjurAuthnResponse=$($CURL -H "Authorization: Basic $ConjurAuthnCreds" -H "Content-Type: application/json" "$BASE_URL/conjur/login")
  test "conjurlogin" "$conjurAuthnResponse"

  # Add LOB user as member of safe for synchronization to Conjur
  safeMemberAdd=$($CURL -X POST --url "$BASE_URL/safe?safeName=$PAS_SAFE_NAME&lobName=$PAS_LOB_NAME")
  test "safeMemberAdd" "$safeMemberAdd"

  read -n 1 -s -r -p "Press any key to continue"
  echo

  # Create Conjur sync policy for project
  authnResponse=$($CURL --request POST --url "$BASE_URL/safe/syncpolicy?vaultName=$PAS_VAULT_NAME&safeName=$PAS_SAFE_NAME&lobName=$PAS_LOB_NAME")
  test "basePolicy" "$authnResponse"

  read -n 1 -s -r -p "Press any key to continue"
  echo

  # Create Conjur base policy for project
  authnResponse=$($CURL --request POST --url "$BASE_URL/project/basepolicy?projectName=$PROJECT_NAME&adminName=$PROJECT_ADMIN")
  test "basePolicy" "$authnResponse"

  read -n 1 -s -r -p "Press any key to continue"
  echo

  # Create Conjur safe consumer group under project's base policy
  authnResponse=$($CURL --request POST --url "$BASE_URL/project/safepolicy?projectName=$PROJECT_NAME&vaultName=$PAS_VAULT_NAME&lobName=$PAS_LOB_NAME&safeName=$PAS_SAFE_NAME")
  test "safePolicy" "$authnResponse"

  read -n 1 -s -r -p "Press any key to continue"
  echo

  # Create Conjur identity under project's base policy
  authnResponse=$($CURL --request POST --url "$BASE_URL/project/identitypolicy?projectName=$PROJECT_NAME&identityName=$PROJECT_IDENTITY")
  test "identityPolicy" "$authnResponse"

  read -n 1 -s -r -p "Press any key to continue"
  echo

  # Grant safe policy role to identity 
  authnResponse=$($CURL --request POST --url "$BASE_URL/project/accesspolicy?projectName=$PROJECT_NAME&identityName=$PROJECT_IDENTITY&groupRoleName=$PROJECT_GROUP_ROLE")
  test "accessgrant" "$authnResponse"
}

###################################
test() {
  if ! $DEBUG; then return; fi
  local funcname=$1; shift
  local value="$(echo $1 | tr -d '\r\n')"; shift

  if [[ $value == null ]]; then
    echo "$funcname returned null."
  else
    echo "$funcname returned:"
    echo "$value"
    echo
  fi
}

main "$@"
